name: Lint Autofix

on: [workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install eslint eslint-plugin-unused-imports --save-dev
      - run: npx eslint pages components lib styles --fix
      - run: git config --global user.name "autofix-bot"
      - run: git config --global user.email "autofix@insidecampus.com"
      - run: git commit -am "Auto-fix ESLint issues" || echo "No changes to commit"
      - run: git push
